In [9]:
from trustworthai.models.core_models.Hypermapp3r import HyperMapp3r
import torch
from trustworthai.models.stochastic_wrappers.deterministic import Deterministic

In [10]:
x = torch.randn(1, 3, 224, 224)

In [59]:
def run_multiple_times(model):
    with torch.no_grad():
        # model.eval()
        out1 = model.cuda()(x.cuda()).cpu()
        out2 = model.cuda()(x.cuda()).cpu()
        print(out1[0, 0, 0, 0:10])
        print(out2[0, 0, 0, 0:10])
        print(out1.shape)

### model should be deterministic

In [60]:
encoder_sizes=[16,32,64,128,256]
base_model = HyperMapp3r(
    dropout_p=0,
    encoder_sizes=encoder_sizes,
    inchannels=3,
    outchannels=2,
    encoder_dropout1=0,
    encoder_dropout2=0,
    decoder_dropout1=0,
    decoder_dropout2=0,
)

model_raw = Deterministic(base_model).cuda()

In [61]:
run_multiple_times(model_raw)

tensor([0.3531, 0.3373, 0.2966, 0.2932, 0.3476, 0.2462, 0.3072, 0.1577, 0.2163,
        0.0695])
tensor([0.3531, 0.3373, 0.2966, 0.2932, 0.3476, 0.2462, 0.3072, 0.1577, 0.2163,
        0.0695])
torch.Size([1, 2, 224, 224])


In [62]:
encoder_sizes=[16,32,64,128,256]
base_model = HyperMapp3r(
    dropout_p=0.2,
    encoder_sizes=encoder_sizes,
    inchannels=3,
    outchannels=2,
    encoder_dropout1=0,
    encoder_dropout2=0,
    decoder_dropout1=0,
    decoder_dropout2=0,
)

model_raw = Deterministic(base_model).cuda()

In [63]:
run_multiple_times(model_raw)

tensor([-0.0051,  0.2040,  0.2168,  0.0789, -0.0879, -0.0422,  0.3120, -0.0650,
         0.2092, -0.0851])
tensor([-0.0051,  0.2040,  0.2168,  0.0789, -0.0879, -0.0422,  0.3120, -0.0650,
         0.2092, -0.0851])
torch.Size([1, 2, 224, 224])


### stochastic 1 encoder first layer:

In [64]:
encoder_sizes=[16,32,64,128,256]
base_model = HyperMapp3r(
    dropout_p=0.2,
    encoder_sizes=encoder_sizes,
    inchannels=3,
    outchannels=2,
    encoder_dropout1=1,
    encoder_dropout2=0,
    decoder_dropout1=0,
    decoder_dropout2=0,
)

model_raw = Deterministic(base_model).cuda()

In [65]:
run_multiple_times(model_raw)

tensor([ 0.1952,  0.0642, -0.0479,  0.1330, -0.1077,  0.0339, -0.0429, -0.1003,
        -0.1019, -0.2133])
tensor([ 0.1323, -0.0821, -0.0644,  0.1344, -0.0923,  0.0506,  0.1692,  0.0611,
         0.1126, -0.1249])
torch.Size([1, 2, 224, 224])


### stochastic 2 encoder second layers:

In [66]:
encoder_sizes=[16,32,64,128,256]
base_model = HyperMapp3r(
    dropout_p=0.2,
    encoder_sizes=encoder_sizes,
    inchannels=3,
    outchannels=2,
    encoder_dropout1=0,
    encoder_dropout2=1,
    decoder_dropout1=0,
    decoder_dropout2=0,
)

model_raw = Deterministic(base_model).cuda()

In [67]:
run_multiple_times(model_raw)

tensor([ 0.2008,  0.1292,  0.0597,  0.0029,  0.0458,  0.2156,  0.1909, -0.0235,
         0.1325, -0.1337])
tensor([-0.0457,  0.0308,  0.0459, -0.0329,  0.0291,  0.0901,  0.1113, -0.0999,
         0.0680, -0.1276])
torch.Size([1, 2, 224, 224])


### stochastic 3 decoder first layer:

In [68]:
encoder_sizes=[16,32,64,128,256]
base_model = HyperMapp3r(
    dropout_p=0.2,
    encoder_sizes=encoder_sizes,
    inchannels=3,
    outchannels=2,
    encoder_dropout1=0,
    encoder_dropout2=0,
    decoder_dropout1=0,
    decoder_dropout2=1,
)

model_raw = Deterministic(base_model).cuda()

In [69]:
run_multiple_times(model_raw)

tensor([ 0.1843,  0.0017, -0.0280,  0.1228,  0.1094,  0.1310,  0.0905,  0.1048,
         0.1020,  0.1251])
tensor([ 0.0385,  0.0511, -0.0757,  0.1059,  0.0676,  0.0828,  0.0904,  0.1508,
         0.1106,  0.0953])
torch.Size([1, 2, 224, 224])


### Stochastic 4 decoder second layer:

In [72]:
encoder_sizes=[16,32,64,128,256]
base_model = HyperMapp3r(
    dropout_p=0.2,
    encoder_sizes=encoder_sizes,
    inchannels=3,
    outchannels=2,
    encoder_dropout1=0,
    encoder_dropout2=0,
    decoder_dropout1=0,
    decoder_dropout2=1,
)

model_raw = Deterministic(base_model).cuda()

In [73]:
run_multiple_times(model_raw)

tensor([-0.2827, -0.3057, -0.2393, -0.2279, -0.1853, -0.1086, -0.1819, -0.1619,
        -0.0869, -0.1261])
tensor([-0.3778, -0.4112, -0.3191, -0.3624, -0.3720, -0.1769, -0.2692, -0.2956,
        -0.2868, -0.2880])
torch.Size([1, 2, 224, 224])
